mysql:
    image: mysql:5.7
    environment:
        MYSQL_DATABASE: rundeck
        MYSQL_USER: rundeck
        MYSQL_PASSWORD: 641949548825f1f8c51d5f547ab88faa
        MYSQL_RANDOM_ROOT_PASSWORD : 'true'
    volumes:
        - ./volume/mysql:/var/lib/mysql
rundeck:
    build: .
    environment:
        MYSQL_DATABASE: rundeck
        MYSQL_USER: rundeck
        MYSQL_PASSWORD: 641949548825f1f8c51d5f547ab88faa
        HOST_RUNDECK: localhost
        SERVER_URL: https://localhost:4443
        PASSWORD: admin
    ports:
        - "4443:4443"
    links:
        - mysql
    volumes:
        - ./volume/etc:/etc/rundeck
        - ./volume/rundeck:/var/rundeck
        - ./volume/lib:/var/lib/rundeck
        - ./volume/log:/var/log/rundeck
